export const COUNTRIES = [
  { code: '+51', iso: 'pe', name: 'Perú' },
  { code: '+52', iso: 'mx', name: 'México' },
  { code: '+54', iso: 'ar', name: 'Argentina' },
  { code: '+57', iso: 'co', name: 'Colombia' },
  { code: '+56', iso: 'cl', name: 'Chile' },
  { code: '+34', iso: 'es', name: 'España' },
  { code: '+1', iso: 'us', name: 'EE.UU./Canadá' },
  { code: '+58', iso: 've', name: 'Venezuela' },
  { code: '+593', iso: 'ec', name: 'Ecuador' },
  { code: '+591', iso: 'bo', name: 'Bolivia' },
  { code: '+595', iso: 'py', name: 'Paraguay' },
  { code: '+598', iso: 'uy', name: 'Uruguay' },
  { code: '+506', iso: 'cr', name: 'Costa Rica' },
  { code: '+502', iso: 'gt', name: 'Guatemala' },
  { code: '+507', iso: 'pa', name: 'Panamá' },
  { code: '+53', iso: 'cu', name: 'Cuba' },
  { code: '+55', iso: 'br', name: 'Brasil' },
  { code: '+44', iso: 'gb', name: 'Reino Unido' },
  { code: '+39', iso: 'it', name: 'Italia' },
  { code: '+49', iso: 'de', name: 'Alemania' },
  { code: '+33', iso: 'fr', name: 'Francia' },
];
